updated content
IEEE-NITK/ieee-nitk.github.io pull request #350
Opened 2022-11-30 13:48 UTC by Shashankhs17

2022-11-30 16:35 UTC, nishant-nayak requested changes
- [ ] Update the button on home landing page from Electrika to Impulse
- [ ] Get the updated registration form link from @Jimmy622 and update the register button
- [ ] Update line 116 to say open to only first and second year students from all over India
- [ ] Ensure that the prizes are updated, as well as the certificates for participants

2022-11-30 16:35 UTC, nishant-nayak commented on impulse.html
>        <a class="btn btn-primary btn-xl js-scroll-trigger" href="https://forms.gle/7AojpxFt5jr44A7N9">Register Now</a>
Update the registration link here.

2022-11-30 16:35 UTC, nishant-nayak commented on impulse.html
> +                          1st or 2nd year engineering students from any engineering college in India are eligible to participate.
Mention B.Tech

2022-11-30 16:35 UTC, nishant-nayak commented on impulse.html
> +                          No. The test will have questions about the basics of Linear Algebra, Signals and Systems, Aptitude and some Python coding. It will not have any competitive coding style ques
Confirm if the prelim test is on Hackerearth or not.

2022-12-01 05:46 UTC, Shashankhs17 commented on impulse.html
> +                          No. The test will have questions about the basics of Linear Algebra, Signals and Systems, Aptitude and some Python coding. It will not have any competitive coding style ques
Confirmed as test is on Hackerearth itself.

2022-12-01 05:52 UTC, Shashankhs17 commented
![Screenshot (329)](https://user-images.githubusercontent.com/78093264/204976182-66dbbbbb-5330-43ed-a626-caad198fb353.png)
![Screenshot (328)](https://user-images.githubusercontent.com/78093264/204976190-edde278f-4faa-4f5a-8d30-2b4eb69744be.png)

2022-12-01 15:41 UTC, Shashankhs17 commented
![image](https://user-images.githubusercontent.com/78093264/205095817-cd2da473-7c18-426b-ada2-e892d8f11f82.png)

2022-12-02 17:35 UTC, nishant-nayak approved these changes
LGTM!

2022-12-02 17:35 UTC, merged